engines:
  rubocop: 
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
  gnu-complexity:
    enabled: true

ratings:
  paths:
  - "**.h"
  - "**.c"
exclude_paths:
  - script/
  - tool/
  - performance/

