engines:
  rubocop: 
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
      config:
        strings:
          - FIXME
          - BUG
          - CUSTOM
  gnu-complexity:
    enabled: true
      config:
        threshold: 100

ratings:
  paths:
  - "**.h"
  - "**.c"
exclude_paths:
  - script/
  - tool/
  - performance/

