C: true
engines:
  rubocop: 
    enabled: true
  fixme:
    enabled: true
    checks:
      HACK:
        enabled: false
  gnu-complexity:
    enabled: true
  duplication:
    enabled: true
      languages:
        c:
  foodcritic:
    enabled: true
ratings:
  paths:
  - "**.h"
  - "**.c"
exclude_paths:
  - script/
  - tool/
  - performance/
script:
  - brew update && brew upgrade codeclimate

