engines:
  rubocop: 
    enabled: true
  duplication:
    enabled: true
      config:
        languages:
          - c
  fixme:
    enabled: true
      config:
        strings:
          - FIXME
          - BUG
          - CUSTOM
  gnu-complexity:
    enabled: true
      config:
        threshold: 100

ratings:
  paths:
  - src/**
  - script/**
exclude_paths:
  - script/
  - tool/
  - performance/

