engines:
  rubocop: 
    enabled: true
  duplication:
    enabled: true
      config:
        languages:
          - c
  fixme:
    enabled: true
      config:
        strings:
          - FIXME
          - BUG
          - CUSTOM
ratings:
  paths: []
exclude_paths:
  - script/
  - tool/
  - performance/

