language: c
compiler:
  - gcc
  - clang
script: 
  - ulimit -s unlimited
  - bash ./script/build.sh DEBUG X86_64 LIBC ELF COVERAGE
  - bash ./script/run_unit_test.sh
  - bash ./script/build.sh RELEASE X86_64 LIBC ELF COVERAGE
  - bash ./output/out/ds.elf -p=10000 *.*.*
  - bash ./script/build.sh RELEASE X86_64 LIBC ELF
  - bash ./script/run_performance_test.sh
notifications:
  email:
    - incarnation.p.lee@outlook.com
install:
  - mkdir lcov && cd lcov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov
  - cd -
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov coverage.info

