language: c
compiler:
  - gcc
  - clang
script: 
  - ulimit -s unlimited
  - bash ./script/build.sh DEBUG X86_64 LIBC
  - bash ./script/run_unit_test.sh
  - bash ./script/build.sh RELEASE X86_64 LIBC
  - bash ./script/run_performance_test.sh
notifications:
  email:
    - incarnation.p.lee@outlook.com

