language: c
compiler:
  - gcc
  - clang
script: 
  - ulimit -s unlimited
  - bash ./script/run_unit_test.sh
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    - incarnation.p.lee@outlook.com
install:
  - mkdir lcov && cd lcov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov
  - cd -
after_success:
  - coveralls-lcov /tmp/coverage.info
  - bash ./script/run_performance_test.sh

