language: c
compiler:
  - gcc
  - clang
script: 
  - bash src/script/build.sh DEBUG=1
  - ls -lR
  - file obj_out/out/ds.elf
  - ldd obj_out/out/ds.elf
  - ./obj_out/out/ds.elf -l -u
notifications:
  email:
    - incarnation.p.lee@outlook.com

