language: c
compiler:
  - gcc
  - clang
script: 
  - bash src/script/build.sh DEBUG=1
  - ls -l obj_out/out/ds.elf
  - uname -a
  - env
  - ./obj_out/out/ds.elf
notifications:
  email:
    - incarnation.p.lee@outlook.com

