language: c
compiler:
  - gcc
  - clang
script: 
  - ulimit -s unlimited
  - bash src/script/build.sh DEBUG=1
  - bash src/script/run_unit_test.sh
  - bash src/script/build.sh DEBUG=0 OPT_HOT=1
  - bash src/script/run_performance_test.sh
notifications:
  email:
    - incarnation.p.lee@outlook.com

