language: c
compiler:
  - gcc
compiler:
  - gcc
  - clang
script: 
  - bash ./script/run_travis_ci_test.sh
notifications:
  email:
    - incarnation.p.lee@outlook.com
install:
  - pip install --user cpp-coveralls
after_success:
  - echo '=== Code Coverage of codecov.io =====' && bash <(curl -s https://codecov.io/bash)
  - echo '=== Code Coverage of coveralls =====' && coveralls --gcov-options '\-lp'

