codecov:
  branch: master 

coverage:
  precision: 4
  round: down
  range: "70...100"

  status:
    project:
      default:
        enabled: yes
        target: auto
        if_no_uploads: error

    patch:
      default:
        if_no_uploads: error

    changes: true

comment:
  layout: "header, diff, changes, suggestions"
  behavior: default

