#ifndef HAVE_DEFINED_queue_H
#define HAVE_DEFINED_queue_H

// Automaticaly generated by script/produce_module_declaration_h.pl.

bool array_queue_empty_p(s_array_queue_t *queue);
bool array_queue_full_p(s_array_queue_t *queue);
bool array_queue_structure_legal_p(s_array_queue_t *queue);
bool doubly_end_queue_empty_p(struct doubly_end_queue *queue);
bool stacked_queue_empty_p(s_stacked_queue_t *queue);
bool stacked_queue_full_p(s_stacked_queue_t *queue);
s_array_queue_t * array_queue_create(void);
s_stacked_queue_t * stacked_queue_create(void);
static inline bool array_queue_empty_ip(s_array_queue_t *queue);
static inline bool array_queue_full_ip(s_array_queue_t *queue);
static inline bool array_queue_resize_front_to_rear_p(s_array_queue_t *queue);
static inline bool array_queue_space_structure_legal_p(s_array_queue_space_t *space);
static inline bool array_queue_structure_legal_ip(s_array_queue_t *queue);
static inline bool doubly_end_queue_empty_p_internal(struct doubly_end_queue *queue);
static inline bool stacked_queue_empty_ip(s_stacked_queue_t *queue);
static inline bool stacked_queue_structure_legal_p(s_stacked_queue_t *queue);
static inline struct doubly_end_queue_list * doubly_end_queue_list_next(struct doubly_end_queue_list *node);
static inline struct doubly_end_queue_list * doubly_end_queue_list_offset_reflect(struct doubly_linked_list *link);
static inline struct doubly_end_queue_list * doubly_end_queue_list_previous(struct doubly_end_queue_list *node);
static inline uint32 stacked_queue_rest_i(s_stacked_queue_t *queue);
static inline void array_queue_resize_expand(s_array_queue_t *queue, uint32 size, void **addr);
static inline void array_queue_resize_i(s_array_queue_t *queue, uint32 size);
static inline void array_queue_resize_narrow(s_array_queue_t *queue, uint32 size, void **addr);
static inline void doubly_end_queue_cleanup_internal(struct doubly_end_queue *queue);
static inline void doubly_end_queue_last_node_clean(struct doubly_end_queue *queue);
static inline void stacked_queue_resize_i(s_stacked_queue_t *queue, uint32 dim);
static inline void stacked_queue_stack_dump(s_array_stack_t *from, s_array_stack_t *to);
struct doubly_end_queue * doubly_end_queue_create(void);
uint32 array_queue_capacity(s_array_queue_t *queue);
uint32 array_queue_rest(s_array_queue_t *queue);
uint32 doubly_end_queue_length(struct doubly_end_queue *queue);
uint32 stacked_queue_capacity(s_stacked_queue_t *queue);
uint32 stacked_queue_rest(s_stacked_queue_t *queue);
void * array_queue_front(s_array_queue_t *queue);
void * array_queue_leave(s_array_queue_t *queue);
void * array_queue_rear(s_array_queue_t *queue);
void * doubly_end_queue_head_leave(struct doubly_end_queue *queue);
void * doubly_end_queue_tail_leave(struct doubly_end_queue *queue);
void * stacked_queue_front(s_stacked_queue_t *queue);
void * stacked_queue_leave(s_stacked_queue_t *queue);
void * stacked_queue_rear(s_stacked_queue_t *queue);
void array_queue_cleanup(s_array_queue_t *queue);
void array_queue_destroy(s_array_queue_t **queue);
void array_queue_enter(s_array_queue_t *queue, void *member);
void array_queue_iterate(s_array_queue_t *queue, void (*handler)(void *));
void array_queue_resize(s_array_queue_t *queue, uint32 size);
void doubly_end_queue_cleanup(struct doubly_end_queue *queue);
void doubly_end_queue_destroy(struct doubly_end_queue **queue);
void doubly_end_queue_head_enter(struct doubly_end_queue *queue, void *member);
void doubly_end_queue_iterate(struct doubly_end_queue *queue, void (*handle)(void *));
void doubly_end_queue_tail_enter(struct doubly_end_queue *queue, void *member);
void stacked_queue_cleanup(s_stacked_queue_t *queue);
void stacked_queue_destroy(s_stacked_queue_t **queue);
void stacked_queue_enter(s_stacked_queue_t *queue, void *member);
void stacked_queue_iterate(s_stacked_queue_t *queue, void (*handler)(void *));
void stacked_queue_resize(s_stacked_queue_t *queue, uint32 dim);

#endif

