#ifndef PERFORMANCE_TEST_DECLARATION_H
#define PERFORMANCE_TEST_DECLARATION_H


static inline double performance_test_reference_variance_calculate(char *name, sint64 period);
static inline sint64 performance_test_time_stamp_period(void);
static inline sint64 performance_test_time_stamp_timeval_unpack(struct timeval *tv);
static inline struct performance_test_reference * performance_test_reference_entry_find_by_name(char *name);
static inline void performance_test_execution_category(const struct test_layer_table *category, struct test_case_filter *filter, struct test_extra_info *info);
static inline void performance_test_execution_implement(const struct test_layer_table *implement, struct test_case_filter *filter, struct test_extra_info *info);
static inline void performance_test_execution_interface(const struct test_layer_table *interface, struct test_case_filter *filter, struct test_extra_info *info);
static inline void performance_test_execution_start(struct test_extra_info *info, char *content);
static inline void performance_test_leftist_heap_create(uint32 count);
static inline void performance_test_leftist_heap_destroy(uint32 count);
static inline void performance_test_leftist_heap_get_min(uint32 count);
static inline void performance_test_leftist_heap_insert(uint32 count);
static inline void performance_test_leftist_heap_merge(uint32 count);
static inline void performance_test_leftist_heap_node_create(uint32 count);
static inline void performance_test_leftist_heap_remove_min(uint32 count);
static inline void performance_test_leftist_heap_remove_min_and_destroy(uint32 count);
static inline void performance_test_leftist_heap_struct_field(uint32 count);
static inline void performance_test_reference_golden_prepare(const char *fname);
static inline void performance_test_reference_new_writeback(const char *fname);
static inline void performance_test_reference_update(char *raw, struct performance_test_reference *ref);
static inline void performance_test_result_print(char *name, sint64 period);
static inline void performance_test_time_stamp_begin(void);
static inline void performance_test_time_stamp_end(void);
static void performance_test_array_queue_capacity(uint32 count);
static void performance_test_array_queue_cleanup(uint32 count);
static void performance_test_array_queue_create(uint32 count);
static void performance_test_array_queue_destroy(uint32 count);
static void performance_test_array_queue_empty_p(uint32 count);
static void performance_test_array_queue_enter(uint32 count);
static void performance_test_array_queue_full_p(uint32 count);
static void performance_test_array_queue_iterate(uint32 count);
static void performance_test_array_queue_leave(uint32 count);
static void performance_test_array_queue_space_expand(uint32 count);
static void performance_test_array_queue_space_rest(uint32 count);
static void performance_test_avl_tree_balanced_p(uint32 count);
static void performance_test_avl_tree_create(uint32 count);
static void performance_test_avl_tree_destroy(uint32 count);
static void performance_test_avl_tree_initial(uint32 count);
static void performance_test_avl_tree_iterate(uint32 count);
static void performance_test_avl_tree_node_contains_p(uint32 count);
static void performance_test_avl_tree_node_create(uint32 count);
static void performance_test_avl_tree_node_find(uint32 count);
static void performance_test_avl_tree_node_find_max(uint32 count);
static void performance_test_avl_tree_node_find_min(uint32 count);
static void performance_test_avl_tree_node_initial(uint32 count);
static void performance_test_avl_tree_node_insert(uint32 count);
static void performance_test_avl_tree_node_remove(uint32 count);
static void performance_test_avl_tree_node_remove_and_destroy(uint32 count);
static void performance_test_avl_tree_struct_field(uint32 count);
static void performance_test_binary_search_tree_create(uint32 count);
static void performance_test_binary_search_tree_destroy(uint32 count);
static void performance_test_binary_search_tree_height(uint32 count);
static void performance_test_binary_search_tree_initial(uint32 count);
static void performance_test_binary_search_tree_iterate(uint32 count);
static void performance_test_binary_search_tree_node_contains_p(uint32 count);
static void performance_test_binary_search_tree_node_create(uint32 count);
static void performance_test_binary_search_tree_node_find(uint32 count);
static void performance_test_binary_search_tree_node_find_max(uint32 count);
static void performance_test_binary_search_tree_node_find_min(uint32 count);
static void performance_test_binary_search_tree_node_initial(uint32 count);
static void performance_test_binary_search_tree_node_insert(uint32 count);
static void performance_test_binary_search_tree_node_remove(uint32 count);
static void performance_test_binary_search_tree_node_remove_and_destroy(uint32 count);
static void performance_test_binary_search_tree_struct_field(uint32 count);
static void performance_test_doubly_end_queue_cleanup(uint32 count);
static void performance_test_doubly_end_queue_create(uint32 count);
static void performance_test_doubly_end_queue_destroy(uint32 count);
static void performance_test_doubly_end_queue_empty_p(uint32 count);
static void performance_test_doubly_end_queue_head_enter(uint32 count);
static void performance_test_doubly_end_queue_head_leave(uint32 count);
static void performance_test_doubly_end_queue_iterate(uint32 count);
static void performance_test_doubly_end_queue_length(uint32 count);
static void performance_test_doubly_end_queue_struct_field(uint32 count);
static void performance_test_doubly_end_queue_tail_enter(uint32 count);
static void performance_test_doubly_end_queue_tail_leave(uint32 count);
static void performance_test_splay_tree_create(uint32 count);
static void performance_test_splay_tree_destroy(uint32 count);
static void performance_test_splay_tree_height(uint32 count);
static void performance_test_splay_tree_initial(uint32 count);
static void performance_test_splay_tree_iterate(uint32 count);
static void performance_test_splay_tree_node_contains_p(uint32 count);
static void performance_test_splay_tree_node_create(uint32 count);
static void performance_test_splay_tree_node_find(uint32 count);
static void performance_test_splay_tree_node_find_max(uint32 count);
static void performance_test_splay_tree_node_find_min(uint32 count);
static void performance_test_splay_tree_node_initial(uint32 count);
static void performance_test_splay_tree_node_insert(uint32 count);
static void performance_test_splay_tree_node_remove(uint32 count);
static void performance_test_splay_tree_node_remove_and_destroy(uint32 count);
static void performance_test_splay_tree_struct_field(uint32 count);
static void performance_test_stacked_queue_capacity(uint32 count);
static void performance_test_stacked_queue_cleanup(uint32 count);
static void performance_test_stacked_queue_create(uint32 count);
static void performance_test_stacked_queue_destroy(uint32 count);
static void performance_test_stacked_queue_empty_p(uint32 count);
static void performance_test_stacked_queue_enter(uint32 count);
static void performance_test_stacked_queue_full_p(uint32 count);
static void performance_test_stacked_queue_iterate(uint32 count);
static void performance_test_stacked_queue_leave(uint32 count);
static void performance_test_stacked_queue_space_expand(uint32 count);
static void performance_test_stacked_queue_space_rest(uint32 count);
static void performance_test_stacked_queue_struct_field(uint32 count);
static void ptest_binary_indexed_tree_add(uint32 count);
static void ptest_binary_indexed_tree_create(uint32 count);
static void ptest_binary_indexed_tree_destroy(uint32 count);
static void ptest_binary_indexed_tree_range_sum(uint32 count);
static void ptest_binary_indexed_tree_sub(uint32 count);
static void ptest_binary_indexed_tree_sum(uint32 count);
static void ptest_skip_linked_list_find_key(uint32 count);
static void ptest_skip_linked_list_insert(uint32 count);
static void ptest_skip_linked_list_key_contains_p(uint32 count);
static void ptest_skip_linked_list_merge(uint32 count);
static void ptest_skip_linked_list_node_create(uint32 count);
static void ptest_skip_linked_list_remove(uint32 count);
static void ptest_skip_linked_list_remove_and_destroy(uint32 count);

#endif
