#include "impl/performance_test_binary_search_tree.c"
#include "impl/performance_test_avl_tree.c"
#include "impl/performance_test_splay_tree.c"
#include "impl/performance_test_binary_indexed_tree.c"
#include "impl/performance_test_trie_tree.c"
