#include "depends.h"
#include "types.h"
#include "defines.h"
#include "util.h"
#include "data_structure_types.h"
#include "data_structure_defines.h"

#include "linked_list_declaration.h"
#include "linked_list.h"
#include "linked_list_optimize.h"

#include "impl/linked_list_debug.c"
#include "impl/doubly_linked_list.c"
#include "impl/single_linked_list.c"
#include "impl/skip_linked_list.c"
#include "impl/linked_list_optimize.c"
